apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cl
  region: us-east-1

availabilityZones: 
  - us-east-1a
  - us-east-1b

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2

