apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeinfo-deployment
  namespace: default
  labels:
    app: nodeinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeinfo
  template:
    metadata:
      labels:
        app: nodeinfo
    spec:
      containers:
        - name: nodeinfo
          image: <account>.dkr.ecr.<region>.amazonaws.com/nodeinfo:latest
          ports:
            - containerPort: 3000

